apiVersion: environment.cloudbees.com/v1alpha1
kind: GitRepository
metadata:
  name: ci-pipeline-workshop-march2024-insurance-frontend                             
  namespace: previews
spec:
  url: https://github.com/ci-pipeline-workshop-march2024/insurance-frontend.git
  apiTokenSecretRef:
    name: beedemo-dev-github-token
  autoUpdateContexts:                           
  - default
